//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace MonEffPro.MmsRepSvr {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorld2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BindDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab2_BindDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab1_BindDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab1_UpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab3_BindDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab3_UpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab5_BindDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab5_UpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab6P1_BindDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Fab6P1_UpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback F05W_BindDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback F05W_UpdateDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetScalarOperationCompleted;
        
        private System.Threading.SendOrPostCallback NowTimeStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback NowTimeStrMiOperationCompleted;
        
        private System.Threading.SendOrPostCallback NowTimeStrKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback NowDayStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback NowTimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::MonEffPro.Properties.Settings.Default.ClosedXML_MmsRepSvr_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event HelloWorld2CompletedEventHandler HelloWorld2Completed;
        
        /// <remarks/>
        public event BindDataSetCompletedEventHandler BindDataSetCompleted;
        
        /// <remarks/>
        public event UpdateDataCompletedEventHandler UpdateDataCompleted;
        
        /// <remarks/>
        public event Fab2_BindDataSetCompletedEventHandler Fab2_BindDataSetCompleted;
        
        /// <remarks/>
        public event Fab1_BindDataSetCompletedEventHandler Fab1_BindDataSetCompleted;
        
        /// <remarks/>
        public event Fab1_UpdateDataCompletedEventHandler Fab1_UpdateDataCompleted;
        
        /// <remarks/>
        public event Fab3_BindDataSetCompletedEventHandler Fab3_BindDataSetCompleted;
        
        /// <remarks/>
        public event Fab3_UpdateDataCompletedEventHandler Fab3_UpdateDataCompleted;
        
        /// <remarks/>
        public event Fab5_BindDataSetCompletedEventHandler Fab5_BindDataSetCompleted;
        
        /// <remarks/>
        public event Fab5_UpdateDataCompletedEventHandler Fab5_UpdateDataCompleted;
        
        /// <remarks/>
        public event Fab6P1_BindDataSetCompletedEventHandler Fab6P1_BindDataSetCompleted;
        
        /// <remarks/>
        public event Fab6P1_UpdateDataCompletedEventHandler Fab6P1_UpdateDataCompleted;
        
        /// <remarks/>
        public event F05W_BindDataSetCompletedEventHandler F05W_BindDataSetCompleted;
        
        /// <remarks/>
        public event F05W_UpdateDataCompletedEventHandler F05W_UpdateDataCompleted;
        
        /// <remarks/>
        public event GetScalarCompletedEventHandler GetScalarCompleted;
        
        /// <remarks/>
        public event NowTimeStrCompletedEventHandler NowTimeStrCompleted;
        
        /// <remarks/>
        public event NowTimeStrMiCompletedEventHandler NowTimeStrMiCompleted;
        
        /// <remarks/>
        public event NowTimeStrKeyCompletedEventHandler NowTimeStrKeyCompleted;
        
        /// <remarks/>
        public event NowDayStrCompletedEventHandler NowDayStrCompleted;
        
        /// <remarks/>
        public event NowTimeCompletedEventHandler NowTimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld2() {
            object[] results = this.Invoke("HelloWorld2", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorld2Async() {
            this.HelloWorld2Async(null);
        }
        
        /// <remarks/>
        public void HelloWorld2Async(object userState) {
            if ((this.HelloWorld2OperationCompleted == null)) {
                this.HelloWorld2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorld2OperationCompleted);
            }
            this.InvokeAsync("HelloWorld2", new object[0], this.HelloWorld2OperationCompleted, userState);
        }
        
        private void OnHelloWorld2OperationCompleted(object arg) {
            if ((this.HelloWorld2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorld2Completed(this, new HelloWorld2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BindDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BindDataSet(string Strsql) {
            object[] results = this.Invoke("BindDataSet", new object[] {
                        Strsql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BindDataSetAsync(string Strsql) {
            this.BindDataSetAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void BindDataSetAsync(string Strsql, object userState) {
            if ((this.BindDataSetOperationCompleted == null)) {
                this.BindDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBindDataSetOperationCompleted);
            }
            this.InvokeAsync("BindDataSet", new object[] {
                        Strsql}, this.BindDataSetOperationCompleted, userState);
        }
        
        private void OnBindDataSetOperationCompleted(object arg) {
            if ((this.BindDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BindDataSetCompleted(this, new BindDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateData(string Strsql) {
            object[] results = this.Invoke("UpdateData", new object[] {
                        Strsql});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDataAsync(string Strsql) {
            this.UpdateDataAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void UpdateDataAsync(string Strsql, object userState) {
            if ((this.UpdateDataOperationCompleted == null)) {
                this.UpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDataOperationCompleted);
            }
            this.InvokeAsync("UpdateData", new object[] {
                        Strsql}, this.UpdateDataOperationCompleted, userState);
        }
        
        private void OnUpdateDataOperationCompleted(object arg) {
            if ((this.UpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDataCompleted(this, new UpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab2_BindDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Fab2_BindDataSet(string Strsql) {
            object[] results = this.Invoke("Fab2_BindDataSet", new object[] {
                        Strsql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Fab2_BindDataSetAsync(string Strsql) {
            this.Fab2_BindDataSetAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab2_BindDataSetAsync(string Strsql, object userState) {
            if ((this.Fab2_BindDataSetOperationCompleted == null)) {
                this.Fab2_BindDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab2_BindDataSetOperationCompleted);
            }
            this.InvokeAsync("Fab2_BindDataSet", new object[] {
                        Strsql}, this.Fab2_BindDataSetOperationCompleted, userState);
        }
        
        private void OnFab2_BindDataSetOperationCompleted(object arg) {
            if ((this.Fab2_BindDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab2_BindDataSetCompleted(this, new Fab2_BindDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab1_BindDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Fab1_BindDataSet(string Strsql) {
            object[] results = this.Invoke("Fab1_BindDataSet", new object[] {
                        Strsql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Fab1_BindDataSetAsync(string Strsql) {
            this.Fab1_BindDataSetAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab1_BindDataSetAsync(string Strsql, object userState) {
            if ((this.Fab1_BindDataSetOperationCompleted == null)) {
                this.Fab1_BindDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab1_BindDataSetOperationCompleted);
            }
            this.InvokeAsync("Fab1_BindDataSet", new object[] {
                        Strsql}, this.Fab1_BindDataSetOperationCompleted, userState);
        }
        
        private void OnFab1_BindDataSetOperationCompleted(object arg) {
            if ((this.Fab1_BindDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab1_BindDataSetCompleted(this, new Fab1_BindDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab1_UpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Fab1_UpdateData(string Strsql) {
            object[] results = this.Invoke("Fab1_UpdateData", new object[] {
                        Strsql});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Fab1_UpdateDataAsync(string Strsql) {
            this.Fab1_UpdateDataAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab1_UpdateDataAsync(string Strsql, object userState) {
            if ((this.Fab1_UpdateDataOperationCompleted == null)) {
                this.Fab1_UpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab1_UpdateDataOperationCompleted);
            }
            this.InvokeAsync("Fab1_UpdateData", new object[] {
                        Strsql}, this.Fab1_UpdateDataOperationCompleted, userState);
        }
        
        private void OnFab1_UpdateDataOperationCompleted(object arg) {
            if ((this.Fab1_UpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab1_UpdateDataCompleted(this, new Fab1_UpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab3_BindDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Fab3_BindDataSet(string Strsql) {
            object[] results = this.Invoke("Fab3_BindDataSet", new object[] {
                        Strsql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Fab3_BindDataSetAsync(string Strsql) {
            this.Fab3_BindDataSetAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab3_BindDataSetAsync(string Strsql, object userState) {
            if ((this.Fab3_BindDataSetOperationCompleted == null)) {
                this.Fab3_BindDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab3_BindDataSetOperationCompleted);
            }
            this.InvokeAsync("Fab3_BindDataSet", new object[] {
                        Strsql}, this.Fab3_BindDataSetOperationCompleted, userState);
        }
        
        private void OnFab3_BindDataSetOperationCompleted(object arg) {
            if ((this.Fab3_BindDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab3_BindDataSetCompleted(this, new Fab3_BindDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab3_UpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Fab3_UpdateData(string Strsql) {
            object[] results = this.Invoke("Fab3_UpdateData", new object[] {
                        Strsql});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Fab3_UpdateDataAsync(string Strsql) {
            this.Fab3_UpdateDataAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab3_UpdateDataAsync(string Strsql, object userState) {
            if ((this.Fab3_UpdateDataOperationCompleted == null)) {
                this.Fab3_UpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab3_UpdateDataOperationCompleted);
            }
            this.InvokeAsync("Fab3_UpdateData", new object[] {
                        Strsql}, this.Fab3_UpdateDataOperationCompleted, userState);
        }
        
        private void OnFab3_UpdateDataOperationCompleted(object arg) {
            if ((this.Fab3_UpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab3_UpdateDataCompleted(this, new Fab3_UpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab5_BindDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Fab5_BindDataSet(string Strsql) {
            object[] results = this.Invoke("Fab5_BindDataSet", new object[] {
                        Strsql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Fab5_BindDataSetAsync(string Strsql) {
            this.Fab5_BindDataSetAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab5_BindDataSetAsync(string Strsql, object userState) {
            if ((this.Fab5_BindDataSetOperationCompleted == null)) {
                this.Fab5_BindDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab5_BindDataSetOperationCompleted);
            }
            this.InvokeAsync("Fab5_BindDataSet", new object[] {
                        Strsql}, this.Fab5_BindDataSetOperationCompleted, userState);
        }
        
        private void OnFab5_BindDataSetOperationCompleted(object arg) {
            if ((this.Fab5_BindDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab5_BindDataSetCompleted(this, new Fab5_BindDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab5_UpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Fab5_UpdateData(string Strsql) {
            object[] results = this.Invoke("Fab5_UpdateData", new object[] {
                        Strsql});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Fab5_UpdateDataAsync(string Strsql) {
            this.Fab5_UpdateDataAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab5_UpdateDataAsync(string Strsql, object userState) {
            if ((this.Fab5_UpdateDataOperationCompleted == null)) {
                this.Fab5_UpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab5_UpdateDataOperationCompleted);
            }
            this.InvokeAsync("Fab5_UpdateData", new object[] {
                        Strsql}, this.Fab5_UpdateDataOperationCompleted, userState);
        }
        
        private void OnFab5_UpdateDataOperationCompleted(object arg) {
            if ((this.Fab5_UpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab5_UpdateDataCompleted(this, new Fab5_UpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab6P1_BindDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Fab6P1_BindDataSet(string Strsql) {
            object[] results = this.Invoke("Fab6P1_BindDataSet", new object[] {
                        Strsql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Fab6P1_BindDataSetAsync(string Strsql) {
            this.Fab6P1_BindDataSetAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab6P1_BindDataSetAsync(string Strsql, object userState) {
            if ((this.Fab6P1_BindDataSetOperationCompleted == null)) {
                this.Fab6P1_BindDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab6P1_BindDataSetOperationCompleted);
            }
            this.InvokeAsync("Fab6P1_BindDataSet", new object[] {
                        Strsql}, this.Fab6P1_BindDataSetOperationCompleted, userState);
        }
        
        private void OnFab6P1_BindDataSetOperationCompleted(object arg) {
            if ((this.Fab6P1_BindDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab6P1_BindDataSetCompleted(this, new Fab6P1_BindDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fab6P1_UpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Fab6P1_UpdateData(string Strsql) {
            object[] results = this.Invoke("Fab6P1_UpdateData", new object[] {
                        Strsql});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Fab6P1_UpdateDataAsync(string Strsql) {
            this.Fab6P1_UpdateDataAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void Fab6P1_UpdateDataAsync(string Strsql, object userState) {
            if ((this.Fab6P1_UpdateDataOperationCompleted == null)) {
                this.Fab6P1_UpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFab6P1_UpdateDataOperationCompleted);
            }
            this.InvokeAsync("Fab6P1_UpdateData", new object[] {
                        Strsql}, this.Fab6P1_UpdateDataOperationCompleted, userState);
        }
        
        private void OnFab6P1_UpdateDataOperationCompleted(object arg) {
            if ((this.Fab6P1_UpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Fab6P1_UpdateDataCompleted(this, new Fab6P1_UpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/F05W_BindDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet F05W_BindDataSet(string Strsql) {
            object[] results = this.Invoke("F05W_BindDataSet", new object[] {
                        Strsql});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void F05W_BindDataSetAsync(string Strsql) {
            this.F05W_BindDataSetAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void F05W_BindDataSetAsync(string Strsql, object userState) {
            if ((this.F05W_BindDataSetOperationCompleted == null)) {
                this.F05W_BindDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnF05W_BindDataSetOperationCompleted);
            }
            this.InvokeAsync("F05W_BindDataSet", new object[] {
                        Strsql}, this.F05W_BindDataSetOperationCompleted, userState);
        }
        
        private void OnF05W_BindDataSetOperationCompleted(object arg) {
            if ((this.F05W_BindDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.F05W_BindDataSetCompleted(this, new F05W_BindDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/F05W_UpdateData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool F05W_UpdateData(string Strsql) {
            object[] results = this.Invoke("F05W_UpdateData", new object[] {
                        Strsql});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void F05W_UpdateDataAsync(string Strsql) {
            this.F05W_UpdateDataAsync(Strsql, null);
        }
        
        /// <remarks/>
        public void F05W_UpdateDataAsync(string Strsql, object userState) {
            if ((this.F05W_UpdateDataOperationCompleted == null)) {
                this.F05W_UpdateDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnF05W_UpdateDataOperationCompleted);
            }
            this.InvokeAsync("F05W_UpdateData", new object[] {
                        Strsql}, this.F05W_UpdateDataOperationCompleted, userState);
        }
        
        private void OnF05W_UpdateDataOperationCompleted(object arg) {
            if ((this.F05W_UpdateDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.F05W_UpdateDataCompleted(this, new F05W_UpdateDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetScalar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object GetScalar(string sql) {
            object[] results = this.Invoke("GetScalar", new object[] {
                        sql});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void GetScalarAsync(string sql) {
            this.GetScalarAsync(sql, null);
        }
        
        /// <remarks/>
        public void GetScalarAsync(string sql, object userState) {
            if ((this.GetScalarOperationCompleted == null)) {
                this.GetScalarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScalarOperationCompleted);
            }
            this.InvokeAsync("GetScalar", new object[] {
                        sql}, this.GetScalarOperationCompleted, userState);
        }
        
        private void OnGetScalarOperationCompleted(object arg) {
            if ((this.GetScalarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScalarCompleted(this, new GetScalarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NowTimeStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NowTimeStr() {
            object[] results = this.Invoke("NowTimeStr", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NowTimeStrAsync() {
            this.NowTimeStrAsync(null);
        }
        
        /// <remarks/>
        public void NowTimeStrAsync(object userState) {
            if ((this.NowTimeStrOperationCompleted == null)) {
                this.NowTimeStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNowTimeStrOperationCompleted);
            }
            this.InvokeAsync("NowTimeStr", new object[0], this.NowTimeStrOperationCompleted, userState);
        }
        
        private void OnNowTimeStrOperationCompleted(object arg) {
            if ((this.NowTimeStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NowTimeStrCompleted(this, new NowTimeStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NowTimeStrMi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NowTimeStrMi() {
            object[] results = this.Invoke("NowTimeStrMi", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NowTimeStrMiAsync() {
            this.NowTimeStrMiAsync(null);
        }
        
        /// <remarks/>
        public void NowTimeStrMiAsync(object userState) {
            if ((this.NowTimeStrMiOperationCompleted == null)) {
                this.NowTimeStrMiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNowTimeStrMiOperationCompleted);
            }
            this.InvokeAsync("NowTimeStrMi", new object[0], this.NowTimeStrMiOperationCompleted, userState);
        }
        
        private void OnNowTimeStrMiOperationCompleted(object arg) {
            if ((this.NowTimeStrMiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NowTimeStrMiCompleted(this, new NowTimeStrMiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NowTimeStrKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NowTimeStrKey() {
            object[] results = this.Invoke("NowTimeStrKey", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NowTimeStrKeyAsync() {
            this.NowTimeStrKeyAsync(null);
        }
        
        /// <remarks/>
        public void NowTimeStrKeyAsync(object userState) {
            if ((this.NowTimeStrKeyOperationCompleted == null)) {
                this.NowTimeStrKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNowTimeStrKeyOperationCompleted);
            }
            this.InvokeAsync("NowTimeStrKey", new object[0], this.NowTimeStrKeyOperationCompleted, userState);
        }
        
        private void OnNowTimeStrKeyOperationCompleted(object arg) {
            if ((this.NowTimeStrKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NowTimeStrKeyCompleted(this, new NowTimeStrKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NowDayStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NowDayStr() {
            object[] results = this.Invoke("NowDayStr", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NowDayStrAsync() {
            this.NowDayStrAsync(null);
        }
        
        /// <remarks/>
        public void NowDayStrAsync(object userState) {
            if ((this.NowDayStrOperationCompleted == null)) {
                this.NowDayStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNowDayStrOperationCompleted);
            }
            this.InvokeAsync("NowDayStr", new object[0], this.NowDayStrOperationCompleted, userState);
        }
        
        private void OnNowDayStrOperationCompleted(object arg) {
            if ((this.NowDayStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NowDayStrCompleted(this, new NowDayStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NowTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime NowTime() {
            object[] results = this.Invoke("NowTime", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void NowTimeAsync() {
            this.NowTimeAsync(null);
        }
        
        /// <remarks/>
        public void NowTimeAsync(object userState) {
            if ((this.NowTimeOperationCompleted == null)) {
                this.NowTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNowTimeOperationCompleted);
            }
            this.InvokeAsync("NowTime", new object[0], this.NowTimeOperationCompleted, userState);
        }
        
        private void OnNowTimeOperationCompleted(object arg) {
            if ((this.NowTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NowTimeCompleted(this, new NowTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorld2CompletedEventHandler(object sender, HelloWorld2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorld2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorld2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BindDataSetCompletedEventHandler(object sender, BindDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BindDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BindDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateDataCompletedEventHandler(object sender, UpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab2_BindDataSetCompletedEventHandler(object sender, Fab2_BindDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab2_BindDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab2_BindDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab1_BindDataSetCompletedEventHandler(object sender, Fab1_BindDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab1_BindDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab1_BindDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab1_UpdateDataCompletedEventHandler(object sender, Fab1_UpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab1_UpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab1_UpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab3_BindDataSetCompletedEventHandler(object sender, Fab3_BindDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab3_BindDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab3_BindDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab3_UpdateDataCompletedEventHandler(object sender, Fab3_UpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab3_UpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab3_UpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab5_BindDataSetCompletedEventHandler(object sender, Fab5_BindDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab5_BindDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab5_BindDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab5_UpdateDataCompletedEventHandler(object sender, Fab5_UpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab5_UpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab5_UpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab6P1_BindDataSetCompletedEventHandler(object sender, Fab6P1_BindDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab6P1_BindDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab6P1_BindDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Fab6P1_UpdateDataCompletedEventHandler(object sender, Fab6P1_UpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Fab6P1_UpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Fab6P1_UpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void F05W_BindDataSetCompletedEventHandler(object sender, F05W_BindDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class F05W_BindDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal F05W_BindDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void F05W_UpdateDataCompletedEventHandler(object sender, F05W_UpdateDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class F05W_UpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal F05W_UpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetScalarCompletedEventHandler(object sender, GetScalarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScalarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScalarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NowTimeStrCompletedEventHandler(object sender, NowTimeStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NowTimeStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NowTimeStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NowTimeStrMiCompletedEventHandler(object sender, NowTimeStrMiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NowTimeStrMiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NowTimeStrMiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NowTimeStrKeyCompletedEventHandler(object sender, NowTimeStrKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NowTimeStrKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NowTimeStrKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NowDayStrCompletedEventHandler(object sender, NowDayStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NowDayStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NowDayStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void NowTimeCompletedEventHandler(object sender, NowTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NowTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NowTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591